### ISSUE TITLE
how to CORS?

### ISSUE THREAD

**Issue by vylink** [contributte/apitte#84]
Hi Guys,

many thanks for your fantastic work!

I'm just wandering, what is the best approach to make "Apitte" available for Ajax POST. Not sure, how to handle responses for "OPTIONS" requests. Any idea? Any documentation? It will be maybe possible using some middleware, but I have no clue how to implement it.

**Comment by mabar** [comment]
You would like to sent headers like `Access-Control-Allow-Origin: *` with all responses, right?
I would prefer a response decorator, middlewares are used too soon. Also endpoint could return new response so you cannot rely on modifications of response through middlewares if you don't return response immediatelly from that middleware.

**Comment by mabar** [comment]
`return $response->withHeader('Access-Control-Allow-Origin', '*');`
```
services:
    decorator.response.cors:
        class: App\Api\Response\ResponseCorsDecorator
        tags: [apitte.core.decorator: [priority: 60, type: handler.after]]
```
